executable            = DRN_job_pfThresTL315_pedUL18_laserCorrUL18.sh
output                = output_pfThresTL315_pedUL18_laserCorrUL18/pfThresTL315_pedUL18_laserCorrUL18.$(ClusterId).$(ProcId).out
error                 = output_pfThresTL315_pedUL18_laserCorrUL18/pfThresTL315_pedUL18_laserCorrUL18.$(ClusterId).$(ProcId).err
log                   = output_pfThresTL315_pedUL18_laserCorrUL18/pfThresTL315_pedUL18_laserCorrUL18.$(ClusterId).log
should_transfer_files = YES
request_memory        = 3.0 GB
+MaxRuntime           = 6*24*60*60
use_x509userproxy     = True
x509userproxy         = /afs/cern.ch/user/b/bbapi/x509up_u177868

+SingularityBind      = "/cvmfs/unpacked.cern.ch/registry.hub.docker.com/fastml"
+SingularityBindCVMFS = True

environment = "HOME=/afs/cern.ch/user/b/bbapi XrdSecPROTOCOL=gsi,unix"

when_to_transfer_output = ON_EXIT_OR_EVICT
request_cpus = $(DETECTED_CORES)

queue arguments from (
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 0 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 200 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 400 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 600 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 800 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 1000 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 1200 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 1400 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 1600 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 1800 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 2000 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 2200 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 2400 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 2600 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 2800 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 3000 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 3200 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 3400 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 3600 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 3800 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 4000 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 4200 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 4400 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 4600 200
    pfThresTL315_pedUL18_laserCorrUL18 /FourPhotonsGunPt5-300_13TeV-pythia8_RunIISummer20UL18_pfThresTL315_pedUL18_laserCorrUL18/bmarzocc-AODSIM-410271f7747bb045accdc008018c65ec/USER 4800 198
)
